Buddy_Circle/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from posts.views import UserHomeFeed

urlpatterns = [
    path('', views.index.as_view(), name='indexpage'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('groups/',include("groups.urls", namespace="groups")),
    path('posts/', include("posts.urls", namespace="posts")),
    path('accounts/', include("django.contrib.auth.urls")),
    path("home/<slug:username>/", UserHomeFeed.as_view(),name="homefeed"),
    path('<slug:username>/home', views.UserHome.as_view(), name='homepage'),
    path('exit/', views.exitpage.as_view(), name='exitpage'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('login/', views.Login.as_view(template_name='accounts/login.html'), name='login'),
    path('all-users/in-buddycircle', views.AllUserView.as_view(), name='allusers'),
    path('profile-details/for/<pk>/', views.UserProfileView.as_view(), name='userprofile'),
    path('edit-profile-details/for/<pk>/', views.EditUserProfile.as_view(), name='edit_userprofile'),
    path('follow-requests/for/<slug:username>/', views.FollowRequests.as_view(), name='follow_requests'),
    path('followed/by/<slug:username>/', views.FollowingList.as_view(), name='following_list'),
    path('<slug:username>/following/', views.FollowersList.as_view(), name='followers_list'),
    path('send-request/to/<slug:follower_username>/', 
        views.SendFollowRequest.as_view(), name='send_follow_request'
    ),
    path('accept-follow-request/from/<slug:follower_username>/', 
        views.AcceptFollowRequest.as_view(), name='accept_request'
    ),
    path('remove/<slug:follower_username>/', views.UnFollowUser.as_view(), name='unfollow'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout')
]

posts/urls.py
from django.urls import path
from . import views

app_name='posts'

urlpatterns = [
    path('', views.PostList.as_view(), name="all"),
    path("new/", views.CreatePost.as_view(), name="create"),
    path("by/<username>/",views.UserPosts.as_view(),name="for_user"),
    path("by/<username>/<int:pk>/",views.PostDetail.as_view(),name="single"),
    path("delete/<int:pk>/",views.DeletePost.as_view(),name="delete"),
]

accounts/models.py
from django.db import models
from django.contrib import auth
from django.utils import timezone
from django.db.models.signals import post_save
from django.dispatch import receiver
from datetime import datetime, date
import uuid

class User(auth.models.User, auth.models.PermissionsMixin):
    user_uuid = uuid.uuid4()
    buddies = models.ManyToManyField('self', blank=True, through="Buddy", symmetrical=False)

    def __str__(self):
        return f'@{self.username}'

class Profile(models.Model):
    GENDERS = (
            ('M', 'Male'),
            ('F', 'Female'),
        )
    user = models.OneToOneField(auth.get_user_model(), null=True, on_delete=models.CASCADE)
    bio = models.TextField(null=True, blank='', default='')
    profile_pic = models.ImageField(upload_to='profilepics/', null=True, blank=True)
    gender = models.CharField(max_length=1, choices=GENDERS, null=True, blank=False)
    dob = models.DateField(null=True, blank=False) 
    age = models.PositiveIntegerField(null=True, blank=True)
    
    def save(self, *args, **kwargs):
        if self.dob != None:
            today = timezone.now()
            self.age = today.year - self.dob.year - ((today.month, today.day) < (self.dob.month, self.dob.day))

        if self.profile_pic == '':
            print('inside propic')
            if self.gender == 'M':
                self.profile_pic = 'profilepics/maledefault.jpg'
            elif self.gender == 'F':
                self.profile_pic = 'profilepics/femaledefault.jpg'
            
        super().save(*args, **kwargs)

    def __str__(self):
        return self.user.username + "'s profile" 

@receiver(post_save, sender=auth.get_user_model())
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

class Buddy(models.Model):
    REQUEST_STATUS_CHOICES = [
        ( 'SENT', 'Request Sent'),
        ( 'DONE', 'Accepted Request'),
        ( 'BLOCK', 'blocked')
    ]
    requested_from = models.ForeignKey(auth.get_user_model(), related_name="requested_from", on_delete=models.CASCADE)
    requested_to = models.ForeignKey(auth.get_user_model(), related_name="requested_to", on_delete=models.CASCADE)
    request_status = models.CharField(max_length=30, blank=True, choices=REQUEST_STATUS_CHOICES,)
    hand_shaked_on = models.DateTimeField(null=True, blank=True)
    
    def save(self, *args, **kwargs):
        if self.request_status == "DONE":
            self.hand_shaked_on = timezone.now()
        super().save(*args, **kwargs)
    
    def __str__(self):
        return f'{self.requested_from.username} {self.request_status} {self.requested_to.username}'

    class Meta:
        unique_together = ("requested_from", "requested_to") 

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import get_user_model

from bootstrap4.widgets import RadioSelectButtonGroup
from .models import Profile

User = get_user_model()

class userCreateForm(UserCreationForm):
    gender = forms.ChoiceField(
        choices=(
            ('M', _('Male')),
            ('F', _('Female'))
        ), 
        widget=forms.RadioSelect
    )

    def clean(self):
        email = self.cleaned_data.get('email')
        username = self.cleaned_data.get('username')

        if len(username) < 8:
            raise ValidationError("Username should contain atleast 8 characters")
        if User.objects.filter(email=email).exists():
            raise ValidationError("The Email you have entered already exists")

        return self.cleaned_data

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'gender', 'email', 'password1', 'password2')


class UserProfileform(forms.ModelForm):
    gender = forms.ChoiceField(
        choices=(
            ('M', _('Male')),
            ('F', _('Female'))
        ), 
        widget=forms.RadioSelect
    )
    dob = forms.DateField(
        label=_('Date of Birth'),
        widget= forms.DateInput(
            attrs={'type': 'date',}))

    class Meta:
        model = Profile
        # exclude = ('user',)
        # but for ordering fields if missed ordering in models
        fields = ['bio', 'dob', 'gender', 'profile_pic']
        widgets = {
            'bio': forms.Textarea(attrs={'cols': 80, 'rows': 3}),
        }

accounts/views.py
from django.views.generic import (
    CreateView, 
    RedirectView, 
    ListView, 
    DetailView,
    UpdateView
)
from django.urls import reverse_lazy, reverse
from django.contrib.auth.mixins import(
    LoginRequiredMixin,
    PermissionRequiredMixin
)
from django.http import HttpResponseRedirect
from django.contrib.auth.views import LoginView
from django.shortcuts import get_object_or_404
from django.contrib import messages
from django.db import IntegrityError
from django.contrib.auth import get_user_model

from . import forms
from .models import Buddy,Profile

User = get_user_model()

class Login(LoginView):

    def get_success_url(self):
        return reverse('homefeed',kwargs={'username':self.request.user.username})

class SignUp(CreateView):
    form_class = forms.userCreateForm
    template_name = 'accounts/signup.html'
    success_url = reverse_lazy('login')

    def form_valid(self, form):
        self.object = form.save()
        signup_user_profile = get_object_or_404(Profile, user=self.object)
        signup_user_profile.gender = form["gender"].value()
        signup_user_profile.save()
        return super().form_valid(form)

class AllUserView(LoginRequiredMixin, ListView):
    model = User
    template_name = 'accounts/all_user_list.html'
    context_object_name = 'useraccounts'
    def get_queryset(self): 
        return User.objects.select_related('profile').order_by('username')

class UserProfileView(LoginRequiredMixin, DetailView):
    model = User
    template_name = 'accounts/userdetails.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        requested_user = context['user']
        following = Buddy.objects.filter(requested_from=requested_user,request_status='DONE').count()
        followers = Buddy.objects.filter(requested_to=requested_user,request_status='DONE').count()
        context["followers_count"] = followers
        context["following_count"] = following
        print(context['user'])
        print(context)
        return context

class EditUserProfile(LoginRequiredMixin, UpdateView):
    model = Profile
    template_name = 'accounts/edit_userdetails.html'
    form_class = forms.UserProfileform

    def get(self, request, *args, **kwargs):
        if int(self.kwargs.get('pk')) != self.request.user.profile.id:
            return HttpResponseRedirect(reverse("accounts:userprofile",kwargs={"pk": self.request.user.id}))
        else:
            return super().get(request, *args, **kwargs)

    def form_valid(self, form):
        requested_user = form.save(commit=False)
        form_input = self.request.POST
        requested_user.user.username = form_input['username']
        requested_user.user.first_name = form_input['firstname']
        requested_user.user.last_name = form_input['lastname']
        requested_user.user.save()
        return super().form_valid(form)

    def get_success_url(self, *args, **kwargs):
        return reverse("accounts:userprofile", kwargs={'pk':self.request.user.id})

class FollowRequests(LoginRequiredMixin, ListView):
    model = Buddy
    template_name = 'accounts/follow_request_list.html'
    context_object_name = 'follow_requests'

    def get_queryset(self):
        this_user = User.objects.filter(username=self.kwargs.get("username")).get()
        self.follow_requests = Buddy.objects.filter(
                                    requested_to = this_user,
                                    request_status = 'SENT'
                                ).all()
        print(self.follow_requests)
        return self.follow_requests

class FollowersList(LoginRequiredMixin, ListView):
    model = Buddy
    template_name = 'accounts/followers_list.html'
    context_object_name = 'followers_list'

    def get_queryset(self):
        this_user = User.objects.filter(username=self.kwargs.get("username")).get()
        print(this_user)
        followers_list = Buddy.objects.filter(
                            requested_to=this_user,
                            request_status='DONE',
                        ).prefetch_related('requested_from','requested_to').all()
        return(followers_list)
 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        print(context)
        return context

class FollowingList(LoginRequiredMixin, ListView):
    template_name = 'accounts/following_list.html'
    model = Buddy
    context_object_name = 'following_list'

    def get_queryset(self):
        print(self.kwargs.get("username"))
        this_user = User.objects.filter(username=self.kwargs.get("username")).get()
        print(this_user)

        following_list = Buddy.objects.filter(
                            requested_from = this_user,
                            request_status = 'DONE',
                        ).prefetch_related('requested_from','requested_to').all()
        return(following_list)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        print(context)
        return context

class SendFollowRequest(LoginRequiredMixin, RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse("accounts:allusers")

    def get(self,  request, *args, **kwargs):
        requested_from = self.request.user
        print(self.kwargs.get("follower_username"))
        requested_to = get_object_or_404(User,username=self.kwargs.get("follower_username"))

        if requested_from.id != requested_to.id:
            try:
                Buddy.objects.create(
                    requested_from=requested_from,
                    requested_to=requested_to,
                    request_status='SENT'
                )
            except IntegrityError:
                messages.warning(self.request,
                    ("Warning, already sent follow request to {}".format(requested_to.username))
                )
            else:
                messages.success(self.request,"Request sent to {}.".format(requested_to.username))

        return super().get(request, *args, **kwargs)

class AcceptFollowRequest(LoginRequiredMixin, RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        return reverse("accounts:follow_requests", kwargs={'username':self.request.user.username})
    
    def get(self, request, *args, **kwargs):
        follower = get_object_or_404(User, username=self.kwargs.get("follower_username"))
        accept_buddy = Buddy.objects.get(
                            requested_from=follower, 
                            requested_to=self.request.user,
                        )
        print(accept_buddy)
        accept_buddy.request_status = "DONE"
        accept_buddy.save()
        return super().get(request, *args, **kwargs)

class UnFollowUser(LoginRequiredMixin, RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        return reverse("accounts:allusers")

    def get(self, request, *args, **kwargs):
        user = User.objects.filter(username=self.kwargs.get("friendname")).get()
        try:
            buddy = Buddy.objects.filter(
                requested_from=self.request.user,
                requested_to=user
            ).get()

        except Buddy.DoesNotExist:
            messages.warning(
                self.request,
                "You both haven't shaked hands"
            )

        else:
            buddy.delete()
            messages.success(
                self.request,
                "You have successfully unfriended."
            )

accounts/templates/accounts/all_user_list.html
{% extends "user_homepage_base.html" %}
{% load static %}
{% block user_base %}
<h2>All Users</h2>
    <br>
    {% if useraccounts.count > 1 %}
        {% for user_account in useraccounts %}
            {% if user_account.username != user.username %}
            <a class="text-dark" href="{% url 'accounts:userprofile' pk=user_account.id %}">
                <div class="media">
                    <img class="rounded-circle mr-3" src="{% static 'profilepics/malepropic.jpg' %}" alt="Generic placeholder image" height="50px" width="50px">
                    <div class="media-body">
                    <h5 class="mt-0">{{ user_account.username | lower }}</h5>
                    <h6 class="mb-0 text-muted">{{ user_account.get_full_name }}</h6>
                    </div>
                </div>
            </a>
            <hr>
            {% endif %}
        {% endfor %}
    {% else %}
    <div class='text-center'>
        <h4>No Active users</h4>
        <h6>Building new community</h6>
    </div>
    {% endif %}
{% endblock %}

accounts/templates/accounts/edit_userdetails.html
{% extends "user_homepage_base.html" %}
{% load bootstrap4 %}

{% block user_base %}
    <h4>Edit Details</h4>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label for="username">Username</label>
            <input type="text" class="form-control" name ="username" id="username" placeholder="Username ex:'Jonny Depp'" maxlength="15" minlength="6" value='{{user.username}}' required>
        </div>
        <div class="form-group">
            <label for="firstname">First Name</label>
            <input type="text" class="form-control" name ="firstname" id="firstname" placeholder="Firstname" maxlength="15" minlength="4" value='{{user.first_name}}' required>
        </div>
        <div class="form-group">
            <label for="lastname">Last Name</label>
            <input type="text" class="form-control" name ="lastname" id="lastname" placeholder="Last Name" maxlength="10" minlength="4" value='{{user.last_name}}' required>
        </div>
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-dark btn-large">Save details</button>
            <a class="btn btn-dark btn-small" href="{% url 'accounts:userprofile' pk=user.id %}">Go back to details</a>
        {% endbuttons %}
    </form>
{% endblock %}

accounts/templates/accounts/follow_request_list.html
{% extends "user_homepage_base.html" %}
{% load static %}
{% block user_base %}
    {% if follow_requests.count != 0 %}
        {% for requests in follow_requests %}
        <div class="card border-dark mb-3">
            <div class="card-body">
                <div class="row">
                    <div class="col-xs-4 col-sm-4 col-md-2">
                        <img src="{% static 'profilepics/malepropic.jpg' %}" alt="..." class="rounded-circle card-img-left" height="100px" width="100px">
                    </div>
                    <div class="col-md-9">
                        <div class="card-body">
                            <h5 class="card-title">{{ requests.requested_from.username | upper }}</h5>
                            <a href="{% url 'accounts:accept_request' follower_username=requests.requested_from.username %}" class="btn btn-primary">Accept follow</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    {% else %}
        <div class='text-center'>
            <h4>No follow requests</h4>
            <h6>Try finding new buddies</h6>
        </div>
    {% endif %}
{% endblock %}

accounts/templates/accounts/followers_list.html
{% extends "user_homepage_base.html" %}
{% load static %}
{% block user_base %}
    <div class="row">
        <div class="col-md-6">
            <h2>My Followers</h2>
        </div>
        <div class="col-md-6 text-right">
            <a href="{%url 'accounts:follow_requests' username=user.username %}" class="btn btn-secondary">follow Requests</a>
        </div>
    </div>
    <br>
    {% if followers_list.count != 0 %}
        {% for followers in followers_list %}
            <div class="card border-dark mb-3">
                <div class="card-body">
                    <div class="row">
                        <div class="col-xs-4 col-sm-4 col-md-2">
                            <img src="{% static 'profilepics/femalepropic.jpg' %}" alt="..." class="rounded-circle card-img-left" height="100px" width="100px">
                        </div>
                        <div class="col-md-9">
                            <div class="card-body">
                                <a href="{% url 'accounts:userprofile' pk=followers.requested_from.id %}">
                                    <h5 class="card-title">{{ followers.requested_from.username | upper }}</h5>
                                    <h6>{{ following.requested_to.get_full_name }}</h6>
                                    <p class="card-text">following since {{ followers.hand_shaked_on }}</p>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% else %}
    <div class='text-center'>
        <h4>No Followers</h4>
        <h6>Try finding new Followers</h6>
    </div>
    {% endif %}
{% endblock %}

accounts/templates/accounts/following_list.html
{% extends "user_homepage_base.html" %}
{% load static %}
{% block user_base %}
    <div class="row">
        <div class="col-md-6">
            <h2>My Following</h2>
        </div>
        <div class="col-md-6 text-right">
            <a href="{%url 'accounts:follow_requests' username=user.username %}" class="btn btn-secondary">follow Requests</a>
        </div>
    </div>
    <br>
    {% if following_list.count != 0 %}
        {% for following in following_list %}
        <div class="card border-dark mb-3">
            <div class="card-body">
                <div class="row">
            <div class="col-xs-4 col-sm-4 col-md-2">
                <img src="{{ following.requested_from.profile.profilepic.url }}" alt="" class="rounded-circle card-img-left" height="100px" width="100px">
            </div>
                <div class="col-md-9">
                    <div class="card-body">
                        <a href="{% url 'accounts:userprofile' pk=following.requested_to.id %}" class="text-dark">
                            <h5 class="card-title">{{ following.requested_to.username }}</h5>
                            <h6>{{ following.requested_to.get_full_name }}</h6>
                            <p class="card-text">Started following on {{ following.hand_shaked_on }}</p>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        </div>
        {% endfor %}
    {% else %}
    <div class='text-center'>
        <h4>No following</h4>
        <h6>Try finding new buddies</h6>
    </div>
    {% endif %}
{% endblock %}

accounts/templates/accounts/friend_list.html
{% extends "user_homepage_base.html" %}
{% load static %}
{% block user_base %}
    <div class="row">
        <div class="col-md-6">
            <h2>My Friends</h2>
        </div>
        <div class="col-md-6 text-right">
            <a href="{%url 'accounts:friend_request_list' username=user.username %}" class="btn btn-secondary">friend Requests</a>
        </div>
    </div>
    <br>
    {% if friends_list.count != 0 %}
        {% for friends in friends_list %}
        <div class="card border-dark mb-3">
            <div class="card-body">
                <div class="row">
            <div class="col-xs-4 col-sm-4 col-md-2">
                <img src="{% static 'profilepics/femalepropic.jpg' %}" alt="..." class="rounded-circle card-img-left" height="100px" width="100px">
            </div>
                <div class="col-md-9">
                    <div class="card-body">
                        <h5 class="card-title">{{ friends.friend.username | upper }}</h5>
                        <p class="card-text">Together since {{ friends.hand_shaked_on }}</p>
                        <a href="{%url 'accounts:removefriend' friendname=friends.friend.username %}" class="btn btn-primary">Remove friend</a>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    {% else %}
    <div class='text-center'>
        <h4>No friends</h4>
        <h6>Try finding new friends</h6>
    </div>
    {% endif %}
{% endblock %}

accounts/templates/accounts/friend_request_list.html
{% extends "user_homepage_base.html" %}
{% load static %}
{% block user_base %}
    {% if friend_requests.count != 0 %}
        {% for requests in friend_requests %}
        <div class="card border-dark mb-3">
            <div class="card-body">
                <div class="row">
                    <div class="col-xs-4 col-sm-4 col-md-2">
                        <img src="{% static 'profilepics/malepropic.jpg' %}" alt="..." class="rounded-circle card-img-left" height="100px" width="100px">
                    </div>
                    <div class="col-md-9">
                        <div class="card-body">
                            <h5 class="card-title">{{ requests.user_requested.username | upper }}</h5>
                            <a href="{%url 'accounts:addfriend' friendname=requests.user_requested.username %}" class="btn btn-primary">Accept follow</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    {% else %}
        <div class='text-center'>
            <h4>No friend requests</h4>
            <h6>Try finding new friends</h6>
        </div>
    {% endif %}
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}

    <h1>Login</h1>
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
        <button type="submit" class="btn btn-primary">Login</button>
        {% endbuttons %}

    </form>

{% endblock content %}
    

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
    
    <h1>Sign Up</h1>
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
        <button type="submit" class="btn btn-primary">Sign Up</button>
        {% endbuttons %}
    </form>

{% endblock content %}

accounts/templates/accounts/userdetails.html
{% extends "user_homepage_base.html" %}
{% load static %}
{% block user_base %}
<div class="container">
    <div class="row">
        <div class="col-md-8">
            {% if user.username == request.user.username %}
            <h3>My Profile</h3>
            {% else %}
            <h3>{{ user.username|upper }}'s Profile</h3>
            {% endif %}
        </div>
        <div class="col-md-4 text-center">
            <li class="list-group-item bg-light">
                <a class="text-dark" href="{%url 'accounts:followers_list' username=user.username%}">Followers
                <span class="badge badge-secondary">{{followers_count}}</span>
                </a>
                <a class="text-dark" href="{%url 'accounts:following_list' username=user.username%}">Following
                <span class="badge badge-secondary ">{{following_count}}</span>
                </a>
            </li>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-md-4">
            <img src="{{ MEDIA_URL }}{{user.profile.profile_pic}}" alt="" width="80%" height="100%">
        </div>
        <div class="col-md-8">
            <h5 class="font-weight-normal">Username : {{ user.username }}</h5>
            <h5 class="font-weight-normal">First Name : {{ user.first_name }} </h5>
            <h5 class="font-weight-normal">Last Name : {{ user.last_name }}</h5>
            <h5 class="font-weight-normal">Email: {{user.email}}</h5>
            <h5 class="font-weight-normal">Date of birth: {{user.profile.dob}}</h5>
            <h5 class="font-weight-normal">Gender: {{user.profile.gender}}</h5>
            <h5 class="font-weight-normal">Age: {{user.profile.age}}</h5>
        </div>
    </div>
    <hr>
    {% if user.username == request.user.username %}
    <a class='btn btn-secondary' href="{% url 'accounts:edit_userprofile' pk=user.profile.id %}">Edit details</a>
    {% else %}
    <a class='btn btn-secondary' href="{% url 'accounts:send_follow_request' follower_username=user.username %}">follow request</a>
    {% endif %}
</div>
{% endblock %}