Buddy_Circle/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from posts.views import UserHomeFeed

urlpatterns = [
    path('', views.index.as_view(), name='indexpage'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('groups/',include("groups.urls", namespace="groups")),
    path('posts/', include("posts.urls", namespace="posts")),
    path('accounts/', include("django.contrib.auth.urls")),
    path("home/<slug:username>/", UserHomeFeed.as_view(),name="homefeed"),
    path('<slug:username>/home', views.UserHome.as_view(), name='homepage'),
    path('exit/', views.exitpage.as_view(), name='exitpage'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('login/', views.Login.as_view(template_name='accounts/login.html'), name='login'),
    path('all-users/in-buddycircle', views.AllUserView.as_view(), name='allusers'),
    path('profile-details/for/<pk>/', views.UserProfileView.as_view(), name='userprofile'),
    path('edit-profile-details/for/<pk>/', views.EditUserProfile.as_view(), name='edit_userprofile'),
    path('follow-requests/for/<slug:username>/', views.FollowRequests.as_view(), name='follow_requests'),
    path('followed/by/<slug:username>/', views.FollowingList.as_view(), name='following_list'),
    path('<slug:username>/following/', views.FollowersList.as_view(), name='followers_list'),
    path('send-request/to/<slug:follower_username>/', 
        views.SendFollowRequest.as_view(), name='send_follow_request'
    ),
    path('accept-follow-request/from/<slug:follower_username>/', 
        views.AcceptFollowRequest.as_view(), name='accept_request'
    ),
    path('remove/<slug:follower_username>/', views.UnFollowUser.as_view(), name='unfollow'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout')
]

posts/urls.py
from django.urls import path
from . import views

app_name='posts'

urlpatterns = [
    path('', views.PostList.as_view(), name="all"),
    path("new/", views.CreatePost.as_view(), name="create"),
    path("by/<username>/",views.UserPosts.as_view(),name="for_user"),
    path("by/<username>/<int:pk>/",views.PostDetail.as_view(),name="single"),
    path("delete/<int:pk>/",views.DeletePost.as_view(),name="delete"),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script><!-- Cloudfare Font CDN -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    
    <title>Buddy Circle</title>
</head>
<body>
    {% load static %}
    <div class="container">
        <nav class='navbar navbar-expand-md navbar-light '>
            {% if user.is_authenticated %}
            <a class="navbar-brand" href="{% url 'homefeed' username=user.username %}" >
            {% else %}
            <a class="navbar-brand" href="{% url 'indexpage' %}" >
            {% endif %}
            
                <img src="{% static 'webapp_icon.png' %}" width="30" height="30" alt="" loading="lazy">
                <strong>Buddy Circle</strong>
            </a>
            <button class="navbar-toggler navbar-light" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto" >
                    {% if user.is_authenticated %}
                    <li style="color: black;">
                    <a class="navbar nav-item nav-link mb-0 h6" href="{% url 'groups:all' %}" >Groups</a>
                    </li>
                    <li><a class="nav-item nav-link mb-0 h6" href="{% url 'groups:create' %}">Create groups</a></li>
                    <li><a class="nav-item nav-link mb-0 h6" href="{% url 'posts:create' %}">Post</a></li>
                    <li class="nav-item dropdown nav-right">
                        <a class="nav-link dropdown-toggle mb-0 h6" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          Account
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="{%url 'accounts:followers_list' username=request.user.username%}">Followers</a>
                            <a class="dropdown-item" href="{%url 'accounts:following_list' username=request.user.username%}">Following</a>
                            <a class="dropdown-item" href="{%url 'accounts:userprofile' pk=request.user.id %}">User Profile</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a>
                        </div>
                      </li>
                    {% else %}
                    <li><a class="nav-item nav-link mb-0 h6" href="{% url 'groups:all' %}" >Groups</a></li>
                    <li><a class="nav-item nav-link mb-0 h6" href="{%url 'accounts:signup'%}">Sign Up</a></li>
                    <li><a class="nav-item nav-link mb-0 h6" href="{%url 'accounts:login'%}">Login</a></li>
                    {% endif %}
                    <li><a class="nav-item nav-link btn text-light btn-dark" href="https://www.linkedin.com/in/abishektvs/" target="_blank" >Creator</a></li>
                </ul>
            </div>
        </nav>
    </div>
    <div class="container">
    <!-- <div class="jumbotron"> -->
        {% block content %}
        {% endblock content %}
    </div>
    </div>

</body>
</html>

templates/exitpage.html
{% extends 'base.html' %}

{% block content %}
    <h1>you have logged out, Visit again</h1>
{% endblock content %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="jumbotron">
    <div  style="text-align: center;">
        <h1>Welcome to Buddy Circle</h1>
        <h3>An exclusive platform to connect friends </h3>

        <h5>Join Our community</h5>
        <p>With supporting people and friends meet up</p>

        <a class="btn btn-dark" href="{%url 'accounts:signup'%}">Sign Up</a>
        <a class="btn btn-dark" href="{%url 'accounts:login'%}">Login</a>
    </div>
</div>

{% endblock content %}
    

templates/user_homepage.html
{% extends "user_homepage_base.html" %}
{% load humanize %}
{% load static %}
{% block user_base %}
<!-- </div> -->
	{% for post in post_list %}
	<div class="card text-left">
		<div class="card-header">
			<a href="{% url 'posts:for_user' username=post.user.username %}">
				<img class="rounded-circle mr-3" src="{{ MEDIA_URL }}{{ user.profile.profile_pic.url }}" alt="not available" height="25px" width="25px">
				<strong>{{ post.user.username }}</strong>
			</a>
		</div>
		<div class="card-body">
			<!-- <h5 class="card-title">Special title treatment</h5> -->
			<p class="card-text">{{ post.message_html|safe }}</p>
			{% if post.group %}
			<span class="card-text"><a href="#">{{ post.group.name }}</a></span>
			{% endif %}
			  <!-- <a href="#" class="btn btn-primary">Go somewhere</a> -->
		</div>
		<div class="card-footer text-muted">
			<time class="time">Posted on - {{ post.created_at }}</time>
		</div>
	</div>
	{% endfor %}
{% endblock %}

templates/user_homepage_base.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="row">
    <div class="col-md-3">
        <div class="card">
          <div class="card-header text-center">
            <img src="{{ request.user.profile.profile_pic.url }}" alt="" class="rounded-circle" height="80px" width="80px">
            <h3 class="card-text mt-3 mb-0">{{ request.user.username }}</h3>
            <br>
            <a class="card-link btn btn-dark" href="{% url 'homefeed' username=request.user.username %}">Home</a>
            <a class="card-link btn btn-dark" href="{% url 'accounts:allusers' %}">Find Buddies</a>
          </div>
          <div class="card-body">
            <h4 class="card-title">Bio</h4>
            <p class="card-text">
              {% if request.user.profile.bio %} {{ request.user.profile.bio }}.
              {% else %} Add text to describe yourself and reach out friends with interesting contents.
              {% endif %} 
            </p>
          </div>
            <ul class="list-group list-group-flush">
              <li class="list-group-item bg-light"><a class="text-dark" href="{%url 'accounts:userprofile' pk=request.user.id %}">My Profile</a></li>
              <li class="list-group-item bg-light"><a class="text-dark" href="{% url 'posts:for_user' username=request.user.username  %}">My posts</a></li>
              <li class="list-group-item bg-light"><a class="text-dark" href="{% url 'groups:all' %}">My Groups</a></li>
            </ul>
            <div class="card-body">
              <a class="card-link btn btn-dark" href="{% url 'accounts:logout' %}">Logout</a>
              <a class="card-link btn btn-dark" href="{% url 'posts:create' %}"><span class="fa fa-angellist"></span> Add Post</a>
            </div>
          </div>
    </div>
    <div class="col-md-9">
      <!-- <div class="card"> -->
        <div class="container text-muted">
            <p class="text-right">Since {{request.user.date_joined}}</p>
        </div>
      <!-- </div> -->
        <div class="container" style="background-color: white;">
          {% block user_base %}

          {% endblock %}
        </div>
    </div>        
{% endblock content %}
    